### ISSUE TITLE
[Issue] Demonstration video would be useful

### ISSUE THREAD

**Issue by Zorklis** [Darkhax-Minecraft/Herd-Mentality#10]
Currently no representation of the mod is shown, a simple video would help it get more downloads if done well

**Comment by Darkhax** [comment]
Thanks for the feedback. I've updated the project description to be a bit more clear about what the mod does and why someone may want to use it. I've also added a gif of the mod in action to help demonstrate it further.

**Comment by Zorklis** [comment]
Looks good now :)
