### ISSUE TITLE
Player gets on fire after clearing the fire resistance effect by command

### ISSUE THREAD

**Issue by yermachello** [Darkhax-Minecraft/Herd-Mentality#11]
https://github.com/Darkhax-Minecraft/Herd-Mentality/assets/7390018/4f5f072a-611d-4b75-bde2-8e8f1ab41f82

**Comment by Darkhax** [comment]
Thanks for the report, although I think this is the wrong GitHub project. Herd Mentality just makes mobs run away from you in a group when you punch them. Was this meant for my other mod Better Burning?

**Comment by yermachello** [comment]
Yeah, sorry, wrong project x)
