### ISSUE TITLE
Add config option to ignore neutral mobs.

### ISSUE THREAD

**Issue by WitheredWasabi** [Darkhax-Minecraft/Herd-Mentality#2]
Mobs such as llamas, pandas, spiders, etc

**Comment by Darkhax** [comment]
Hello,

I am not sure if I am misunderstanding something, but what you've described seems to be the point of this mod.

**Comment by WitheredWasabi** [comment]
Ah is this intended? Wasn't aware that this was supposed to reach out to neutral mobs also. Would it be possible of neutral mob herd mentality was a config option that you could turn off, because imo its not fun having a group of spiders start attacking you after having hit one.
