### ISSUE TITLE
Hostile mobs should be excluded from notifying

### ISSUE THREAD

**Issue by Knito58** [Darkhax-Minecraft/Herd-Mentality#4]
Notably bosses like the End Dragon.

**Comment by Darkhax** [comment]
Are there any game breaking bugs with the ender dragon being notified? This mod will only notify mobs of the same type within a short block range so ender dragons are likely to be completely unaffected by this mod unless you are spawning in more than one at a time. 

If you must remove the ender dragon for something specific to your world/pack/server you can add the ender dragon to the herdmentality:ignored_mobs tag

**Comment by Knito58** [comment]
The ender dragon notify was in the latest log when the game froze the 5th time during killing the ender dragon. But there were other mods too, which went wild during the end fight and really blocked the game.
This is only a suggestion.
I saw this in the logs and thought you wanted to consider this.
What you already did.
Thank you.
